# Generated by Django 2.2.5 on 2019-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=25, unique=True)),
                ('latest_update', models.DateTimeField(auto_now=True)),
                ('primary_enemy_inference', models.CharField(blank=True, max_length=200)),
                ('primary_team_inference', models.CharField(blank=True, max_length=200)),
                ('latest_model_trained', models.DateTimeField(blank=True)),
            ],
        ),
    ]
