# Generated by Django 2.2.5 on 2019-11-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='primary_enemy_inference',
        ),
        migrations.RemoveField(
            model_name='gamedata',
            name='primary_team_inference',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='inference_primary_enemy',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='inference_primary_team',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='inference_secondary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
