# Generated by Django 2.2.5 on 2019-11-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winrate_backend', '0002_auto_20191108_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedata',
            old_name='inference_primary_enemy',
            new_name='inference_enemy',
        ),
        migrations.RenameField(
            model_name='gamedata',
            old_name='inference_primary_team',
            new_name='inference_team',
        ),
    ]
