# Generated by Django 2.2.5 on 2019-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate_backend', '0003_auto_20191108_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='inference_enemy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='inference_secondary',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='inference_team',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
