# Generated by Django 2.2.5 on 2019-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winrate_backend', '0004_auto_20191108_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='inference_enemy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='inference_secondary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='inference_team',
            field=models.TextField(blank=True),
        ),
    ]
